name: Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 1 * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: ./build.sh
    - name: Log in to GitHub
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: echo ${DOCKER_HUB_PASSWORD} | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    - name: Push image
      run: docker push chcjonathanguo/laravel-installer:latest
    - name: Commit Dockerfile
      uses: stefanzweifel/git-auto-commit-action@v2.0.0
      with:
        commit_author_email: coderjono@gmail.com
        commit_author_name: Jonathan Guo
        commit_message: Apply automatic changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
